### ISSUE TITLE
Image building error

### ISSUE THREAD

**Issue by mrengineer** [hz12opensource/libresdr#7]
Hello! Please, help me with my problem

I am using Ubuntu 22.04.4 LTS, Vivado 2022.2 Vitis & Vivado

When I try to do "make" I get

```
*** buffer overflow detected ***: terminated
Aborted (core dumped)
make[1]: *** [Makefile:1187: u-boot] Error 134
make[1]: exit directory «/home/user/libresdr/plutosdr-fw_0.38_libre/u-boot-xlnx»
make: *** [Makefile:76: u-boot-xlnx/tools/mkimage] Error 2
```
Since I have a lot of software intalled, I have prepared docker

```
FROM ubuntu:22.04
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y --no-install-recommends apt-utils git mc libgmp-dev build-essential fakeroot libncurses5-dev libssl-dev ccache u-boot-tools 
RUN apt-get -y install mtools bc python3 cpio zip unzip rsync file 
RUN apt-get -y install wget flex bison language-pack-en libtinfo5 x11-utils xvfb dbus-x11 libswt-glx-gtk-4-jni libgtk2.0-0
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install libmpc-dev dfu-util device-tree-compiler

WORKDIR /workspace
RUN git clone https://github.com/hz12opensource/libresdr.git
RUN mkdir /tools
```

and docker-compose.yml

```
version: "3.5"

services:
  libre_builder:
    container_name: librsdr_img
    restart: always
    build: .
    image: librsdr_img
    #entrypoint: bash
    volumes:
      - /home/user:/tools
      - .:/workspace
    network_mode: host
    command: bash
```
next in container's cli I do everything and finaly ```make```
Finally, everything is finished OK:
```
...
legal-info/sources/wpa_supplicant-2.10/0002-wpa_supplicant-use-a-less-generic-name-for-IEEE802.1.patch
legal-info/sources/wpa_supplicant-2.10/0001-build-re-enable-options-for-libwpa_client.so-and-.patch
legal-info/sources/wpa_supplicant-2.10/0003-Include-HMAC-SHA384-512-KDF-for-SAE-if-SHA384-512-is.patch
legal-info/sources/wpa_supplicant-2.10/wpa_supplicant-2.10.tar.gz
legal-info/sources/wpa_supplicant-2.10/series
legal-info/sources/libxml2-2.10.4/
legal-info/sources/libxml2-2.10.4/libxml2-2.10.4.tar.xz
rm linux/arch/arm/boot/dts/zynq-libre.dtb
```
and after ```make sdimg``` I see
```
mkdir /workspace/libresdr/plutosdr-fw_0.38_libre/build_sdimg
cp build/sdk/fsbl/Release/fsbl.elf 	/workspace/libresdr/plutosdr-fw_0.38_libre/build_sdimg/fsbl.elf  
cp: cannot stat 'build/sdk/fsbl/Release/fsbl.elf': No such file or directory
make: *** [Makefile:202: sdimg] Error 1
```

**Question: why is fail? What I have to do?**
